include "common.fbs";

namespace mirages.socket;


table TimeRequest {
    session_id: string;
}

table HealthRequest {
    session_id: string;
}


table HealthReply {
    healthy : bool;
    status : HealthStatus;
}

table TimeReply {
    time: Time (required);
}



table AttachRequest {
    run_id: string;
    
    /// data to send to the run's stdin. The server will read from this stream and write to the run's stdin.
    stream: StreamData;
}



table AttachReply {
    data: StreamData;
    exit: RunExit;
}

rpc_service Daemon {
    Health(HealthRequest) : HealthReply;
    Time(TimeRequest) : TimeReply;    

    AttachRun(AttachRequest) : AttachReply (streaming: "server");
}

