# Run ShellCheck (https://www.shellcheck.net/) over all shell scripts
# in the repository
name: ShellCheck
on:
  pull_request:
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'
permissions:
  contents: read
jobs:
  shellcheck:
    name: Run ShellCheck over shell scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 #v2.0.0
